src/guide/installation.md
=> Translate Essentials > Installation into ja

src/guide/a11y-standards.md
Accessibility > Standards の翻訳
https://github.com/vuejs-jp/ja.vuejs.org/issues/47
=> docs: translation Accessibility > Standards 

src/guide/typescript-support.md
=> Tooling > TypeScript Support

src/guide/component-custom-events.md
=> docs: #15 Custom Eventsの翻訳

src/guide/forms.md
=> docs: #10 Essentials > Form Input Bindings の翻訳

src/guide/ssr.md
resolve #44 
v2とv3の英文はほとんど同じだったので、基本的にv2の和訳を踏襲しました。記号の使い方が変更されている箇所がありましたが、文章のニュアンスは変化していないと判断してv2の和訳のままにしました。
`Cordova apps - all` と `Cordova apps—all`
```
Quasar is a node.js and webpack based development environment that supercharges and streamlines rapid development of SPA, PWA, SSR, Electron, Capacitor and Cordova apps - all from one codebase.
```
```
Quasar is a node.js and webpack based development environment that supercharges and streamlines rapid development of SPA, PWA, SSR, Electron, Capacitor and Cordova apps—all from one codebase.
```
=> docs: Translate Scaling Up > Server-Side Rendering

src/guide/change-detection.md
resolve #38 
Render Mechanisms > Change Detection Caveats in Vue 2 の翻訳
=> Render Mechanisms > Change Detection Caveats in Vue 2 の翻訳

src/guide/routing.md
resolve #42 
Scaling Up > Routing の翻訳
[v2](https://jp.vuejs.org/v2/guide/routing.html#%E5%85%AC%E5%BC%8F%E3%83%AB%E3%83%BC%E3%82%BF)の翻訳を参考にしながら[Vue.js 公式サイト日本語翻訳ガイド](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md)に沿った翻訳を心掛けました．
レビューをお願いします．
=> docs: #42 Scaling Up > Routing の翻訳

src/guide/reactivity-fundamentals.md
resolve #31
Advanced Guides > Reactivity Fundamentals の翻訳
=> docs: Advanced Guides > Reactivity Fundamentals の翻訳 (#31)

src/guide/conditional.md
resolve #7 
Vue2の文章とほぼ変わらなかったので、ほとんどVue2の文章を引用しています。
↓の部分で `テンプレート` ではなく、`<template>`としています。
https://github.com/vuejs-jp/ja.vuejs.org/compare/lang-ja...noliaki:translate-conditional_rendering#diff-05d26db877d00579eaa2b28cb102443fR18
Vue2のドキュメント: https://jp.vuejs.org/v2/guide/conditional.html#%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%81%A7%E3%81%AE-v-if-%E3%81%AB%E3%82%88%E3%82%8B%E6%9D%A1%E4%BB%B6%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97
**`v-if` with `v-for`** の部分で、以下のドキュメントでは **`v-for`は`v-if`よりも優先度が高い**との旨が記載されていると思うのですが、
- https://v3.vuejs.org/guide/conditional.html#v-if-with-v-for
- https://v3.vuejs.org/guide/list.html#v-for-with-v-if
以下のマイグレーションガイドだと、 **`v-if`は常に`v-for`よりも優先される**といった旨が記載されています。
- https://v3.vuejs.org/guide/migration/v-if-v-for.html#_3-x-syntax …
=> docs: Translate | Essentials > Conditional Rendering

src/guide/a11y-semantics.md
=> docs:translate guide/a11y-semantics

src/guide/composition-api-lifecycle-hooks.md
resolve #34 
CIがコケるようです(他のPRでも見受けられますが...)。こちら側の不手際がございましたら、大変恐縮ですが、ご教示いただけませんでしょうか？
=> docs: Advanced Guides > Compotion API > Lifecycle Hooks の翻訳 #34

src/guide/composition-api-template-refs.md
resolve #36 
https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs の翻訳をした
=> Advanced Guides > Compotion API > Template Refs の翻訳

src/guide/events.md
Essentials > Event Handling の翻訳
https://v3.vuejs.org/guide/events.html 
https://jp.vuejs.org/v2/guide/events.html
を参考に翻訳
特になし
=> docs: Essentials > Event Handling の翻訳

package.json, src/.textlintrc
resolve #95 
package.jsonファイルの`lint`スクリプトの内容など、基本的に全て`v2`を参照しましたが、修正点ありましたら教えていただけますと助かります🙇‍♀️
=> textlint の導入

.github/workflows/pr.yaml
- `secrets.GITHUB_TOKEN` は固定化されたトークンであり、その PR 発行者の GitHub のトークンを利用する
- そのため権限のないユーザーからの PR については、適切にラベルを付与する処理ができない
- 暫定的対処として、現状存在が特に必要ない処理を STOP する
- `JA_GITHUB_TOKEN` を用意し、 @potato4d の個人アカウントを紐付ける事も考えたが、アクセスコントロールを狭めることができないためセキュリティ上難しい
- @vuejs-jp-bot でトークンを発行する手段はあるが、その場合該当 Bot がそのトークンにてアクセスできる範囲を最小化することが必要となる（public repo へのアクセスくらいの粒度しかできないので、難しそう）
=> chore: Temporary disable tag alert actions

src/guide/migration/events-api.md
resolve #113 
v3.vuejs.org/guide/migration/events-api.html を翻訳しました。
レビューお願い致します！:pray:
=> Migration Guide > Events API の翻訳

src/guide/migration/fragments.md
resolve #115 
https://v3.vuejs.org/guide/migration/fragments.html を翻訳しました！
=> Translate: Migration Guide > Fragments

.github/CONTRIBUTING.md
JTFのガイドの説明などのリンクを明確に用意するため、 CONTRIBUTING.md を v2 doc から持ってきました。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md
=> chore: Add CONTRIBUTING.md

src/guide/migration/inline-template-attribute.md
resolve https://github.com/vuejs-jp/ja.vuejs.org/issues/119
preview: https://deploy-preview-145--vuejs-v3-ja-doc-preview.netlify.app/guide/migration/inline-template-attribute.html
レビューよろしくお願いしますmm
=> Migration Guide > Inline Template Attribute の翻訳

src/guide/migration/global-api-treeshaking.md
this resolves #118 
[v3.vuejs.org/guide/migration/global-api-treeshaking.html](https://v3.vuejs.org/guide/migration/global-api-treeshaking.html) こちらの翻訳です。
よろしくお願いいたします。
=> Migration > Global API Treeshaking の翻訳

src/.vuepress/config.js, src/guide/migration/array-refs.md
resolve #107
https://v3.vuejs.org/guide/migration/array-refs.html を翻訳しました！
対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/array-refs.md が存在しなかったので、https://github.com/vuejs/docs-next/blob/master/src/guide/migration/array-refs.md から取得して追加しました。
また、サイドバーから当該ページを開けるよう、 src/.vuepress/config.js も編集しています。
=> Migration Guide > v-for Array Refs の翻訳

src/guide/migration/async-components.md
resolve #108 
<https://v3.vuejs.org/guide/migration/async-components.html> を翻訳しました！
=> Migration Guide > Async Components の翻訳

src/guide/migration/render-function-api.md
resolves #123 
https://deploy-preview-144--vuejs-v3-ja-doc-preview.netlify.app/guide/migration/render-function-api.html で動作を確認できます。
=> Migration Guide > Render Function API の翻訳

src/guide/migration/attribute-coercion.md
resolve #109 
[v3.vuejs.org/guide/migration/attribute-coercion.html](v3.vuejs.org/guide/migration/attribute-coercion.html) を翻訳しました。
レビューお願い致します！🙏
=> Migration Guide > Attribute Coercion Behavior の翻訳

.github/workflows/sync.yaml
本家の内容を一度に取り込んでしまいたいが、 #150 の方針を取るために定期的に本家の内容を master に反映しておき、 lang-ja -> master への rebase のサイズ感を確認したい。
手動でやっても良いが、忘れかねない。
定期的に master の内容を更新する GitHub Actions を用意した。
GitHub Actions の cron は only running at default branch なので、コードにミスはあるかもしれない
=> chore(CI): Add upstream sync script

src/.vuepress/config.js, src/guide/migration/props-default-this.md
resolve #122 
@potato4d  @vuejs-jp/contributers 
まだ担当割り当てされていないですが、時間が空いていたので対応してしまいました。。
翻訳元ファイルが本リポジトリに存在しなかったので、
https://github.com/vuejs/docs-next/blob/master/src/guide/migration/props-default-this.md 
からコピーしてきました。そして、日本語に翻訳しました。
よろしければレビューをお願いいたします！
=> Migration Guide > Props Default Function `this` Access の翻訳元ファイル追加と翻訳

src/guide/migration/keycode-modifiers.md
resolve #121
https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/keycode-modifiers.md
こちらの翻訳です
遅くなってすみません。レビューよろしくお願いします！
=> Translate: Migration Guide > KeyCode Modifiers

.github/workflows/sync.yaml
https://github.com/vuejs-jp/ja.vuejs.org/runs/1388009636?check_suite_focus=true
> Please make sure you have the correct access rights
and the repository exists.
前回の修正では不十分でした:bow:
upstream を ssh で取得しないように修正しました。
また、waring が出ていたので `git config pull.rebase false` をつけるよう修正しました。
=> fix(ci): fix sync workflow

src/guide/migration/v-model.md
resolve #126 
https://v3.vuejs.org/guide/migration/v-model.html の内容を翻訳しました！
翻訳元の英語ファイルが本家の最新と同じでしたので、英語ファイルは更新せず単純に翻訳だけしました。
@potato4d 
ご確認をお願いいたします🙏
=> Migration Guide > v-model の翻訳

src/guide/migration/global-api.md
resolve #117
おそくなりましたが
https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/global-api.md
を翻訳しました。
よろしくお願いします :bow:
=> Translate: Migration Guide > Migration > GlobalAPI

src/.vuepress/config.js, src/guide/migration/v-if-v-for.md
migration/v-if vs. v-for Precedenceの翻訳
ファイル構成は英語版ガイドを参考にしました。
不要であればマージ無しでcloseしてください。
下記で確認できます。
https://deploy-preview-169--vuejs-v3-ja-doc-preview.netlify.app/guide/migration/v-if-v-for.html#%E6%A6%82%E8%A6%81
=> v-if vs. v-for Precedenceの翻訳

src/examples/commits.md, src/examples/elastic-header.md, src/examples/grid-component.md, src/examples/markdown.md, src/examples/modal.md, src/examples/select2.md, src/examples/svg.md, src/examples/todomvc.md, src/examples/tree-view.md
Example セクションのタイトルとコンテンツの翻訳
基本的には Vue 2.x から要素が一部オミットされている状態なのでそのまま訳を移行しつつ、 Codesandbox の言及が CodePen に変わっている部分などについて細かな追従を行いました。
=> docs(example): Translate examples

src/api/application-api.md
This PR is a part of #177 
Application API を翻訳しました。
=> doc: Translate application api

src/api/application-config.md
This PR is part of #177 
API Reference > API Config を翻訳しました。
サンプルコードの typo は[本家に PR を送っています](https://github.com/vuejs/docs-next/pull/736)が、どのみち一緒なのでこちらでも直しています。
=> doc: Translate API Configuration in Reference

src/style-guide/README.md
#138 の `Priority B` の翻訳
こちら、冒頭文と同じく、ほぼVue 2の翻訳ドキュメントを流用できました。
流用できなかったの翻訳箇所は以下です。
`Vue.component` → `app.component`
560行目
But they'll **never** contain global state (e.g. from a Vuex store).
↓
しかし、それらにはグローバルな状態(例:Vuexストアからのもの)は含まれ**ません**。
895,896行目
- It's rare that global components are ever referenced in JavaScript, so following a convention for JavaScript makes less sense.
↓
- グローバルコンポーネントを JavaScript から参照することはほとんどないので、 JavaScript の原則に従う意味もほとんどありません。
- These applications always include many in-DOM templates, where [kebab-case **must** be used](#Component-name-casing-in-templates-strongly-recommended).
↓
- そのようなアプリケーションはたくさんの DOM 内テンプレート をもつのが常ですが、 そこでは [ケバブケースを **必ず** 使う必要があります](#テンプレート内でのコンポーネント名の形式-強く推奨)
ご確認をよろしくおねがいします🙏
=> translate style guide priority b (#138)

src/guide/component-slots.md
`**ない**` ですと、内容がない意味づけと考えます
`**要素を含まない**` にすると、内容のある意味づけとなり改善します
公式ページでの該当箇所
https://v3.ja.vuejs.org/guide/component-slots.html#スロットコンテンツ:~:text=%E8%A6%81%E7%B4%A0%E3%82%92%E5%90%AB%E3%81%BE-,%E3%81%AA%E3%81%84
=> refact strongの意味づけを「ない」から「要素を含まない」に修正した

src/guide/composition-api-setup.md
>-`props` はリアクティブなので、props のリアクティブを削除してしまうため、**ES6 の分割代入を使うことができません。**
「リアクティブだから、props のリアクティブを削除してしまう」というように受け取れてしまいます。
原文でも、次のように先に結論を述べた後で、
>because props are reactive, you cannot use ES6 destructuring 
次のように根拠を説明しています。
>because it will remove props reactivity.
原文に沿った説明になるように修正しました。
ja: https://v3.ja.vuejs.org/guide/composition-api-setup.html#プロパティ:~:text=%E3%81%97%E3%81%8B%E3%81%97%E3%80%81props%20%E3%81%AF%E3%83%AA%E3%82%A2%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96%E3%81%AA%E3%81%AE%E3%81%A7%E3%80%81props%20%E3%81%AE%E3%83%AA%E3%82%A2%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96%E3%82%92%E5%89%8A%E9%99%A4%E3%81%97%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86%E3%81%9F%E3%82%81%E3%80%81ES6%20%E3%81%AE%E5%88%86%E5%89%B2%E4%BB%A3%E5%85%A5%E3%82%92%E4%BD%BF%E3%81%86%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D …
=> refact composition APIの文章を改善した

src/guide/composition-api-setup.md
表題の通りです
原文の方は先程PRが取り込まれました
https://github.com/vuejs/docs-next/pull/858
実ページでの該当箇所
https://v3.ja.vuejs.org/guide/composition-api-setup.html#プロパティ:~:text=const%20%7B%20title%20%7D%20%3D%20toRefs(props),console.log(title.value)
=> サンプルで使われているタブを2スペースにしました(Composition APIのセットアップページ)

src/api/application-config.md
「AにBに設定」という文に違和感があります
「AをBに設定」という文への変更を提案します
ja: https://v3.ja.vuejs.org/api/application-config.html#performance:~:text=%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%81%AE%E5%88%9D%E6%9C%9F%E5%8C%96%E3%81%AB%20true%20%E3%81%AB%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B
en: https://v3.vuejs.org/api/application-config.html#performance:~:text=Set%20this%20to%20true%20to%20enable%20component%20init
=> 「初期化にtrueに設定」 を 「初期化でtrueに設定」に変更した(アプリケーション構成ページ)

src/api/instance-methods.md, src/guide/component-basics.md, src/guide/component-custom-events.md
emit周りのドキュメントが古く、kebab caseで書かれていました
camelが正しいです
emit周りをcamel caseに修正(更新)しました
(差異アップデート準備中とのことで、焼石に水な本PRは余計なお手間になってしまうかもしれません)
原文
https://github.com/vuejs/docs-next/blob/master/src/api/instance-methods.md
https://github.com/vuejs/docs-next/blob/master/src/guide/component-basics.md
https://github.com/vuejs/docs-next/blob/master/src/guide/component-custom-events.md
=> emitの指定をcamelに修正した(原文に追従)

src/guide/migration/array-refs.md
ref. #202
Migration > Array Refs を本家の master に追従しました。
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/array-refs.md
前回からの差分
https://github.com/vuejs/docs-next/commit/24c809e57b0019a699483a56c3ad6338b0618cbe
close #202
=> Migration > Array Refs の翻訳を追従

src/.vuepress/config.js, src/guide/migration/listeners-removed.md
Migration > Listeners Removed を本家の master に追従しました。
ref. #221 
close #221
=> Migration > Listeners Removed の翻訳を追従

src/.vuepress/config.js, src/guide/migration/watch.md
Migration > Watch を本家の master に追従しました。
ref. #235 
close #235
=> Migration > Watch の翻訳を追従

src/.vuepress/config.js, src/guide/migration/v-on-native-modifier-removed.md
Migration > v-on.native modifier removed を本家の master に追従しました。
ref. #233 
close #233
=> Migration > v-on-native-modifier-removed の翻訳を追従

src/guide/migration/vnode-lifecycle-events.md
Migration > VNode Lifecycle Events を master に追従しました。
ref. #234 
close #234
=> Migration > Vnode Lifecycle Events の翻訳を追従

src/guide/migration/transition-group.md
Migration > Transition Group を本家の master に追従しました。
ref. #228 
close #228
=> Migration > Transition Group の翻訳を追従

src/guide/migration/global-api-treeshaking.md
Migration > Global API Treeshaking を master に追従しました。
ref. #215 
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/global-api-treeshaking.md
前回からの差分
https://github.com/vuejs/docs-next/commit/c281bb8af3fe2bf74bde67e42c3fe6fe242aa230#diff-2817ca271fd5365e71d60136cee9b4ae5debca6f6aa09cfd0a0993ac130f24ff
https://github.com/vuejs/docs-next/commit/8cbc585fa06cb92b76a77da5a1162fd4c6290c47#diff-2817ca271fd5365e71d60136cee9b4ae5debca6f6aa09cfd0a0993ac130f24ff
英語としてのタイポや単語の重複など文法の修正なので、差分なしと取り扱って大丈夫そうです。
#94 にしたがって、表記ゆれを修正しました。
close #215
=> Migration > Global Api Treeshaking の翻訳を追従

src/guide/migration/global-api.md
Migration > Global API を master に追従しました。
ref. #216 
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/global-api.md
前回からの差分
https://github.com/vuejs/docs-next/commit/7b110ff015c9db8f4ff7a0c8167f1be320dbc5a8#diff-6661b581434177761e544ef3af1f1c035fad38946f1c8619e45840c5a8bf7941
https://github.com/vuejs/docs-next/commit/567c9a8e3fd7b6f8c69d69f9bc909cbc31f45c62#diff-6661b581434177761e544ef3af1f1c035fad38946f1c8619e45840c5a8bf7941
https://github.com/vuejs/docs-next/commit/e2c8359aa4917a81a8945ed4ab470871a3219f9b#diff-6661b581434177761e544ef3af1f1c035fad38946f1c8619e45840c5a8bf7941
close #216
=> Migration > Global Api の翻訳を追従

src/guide/migration/keycode-modifiers.md
Migration > Keycode Modifiers を master に追従しました。
ref. #220 
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/keycode-modifiers.md
最新のコミットまで確認して、特に差分が見つかりませんでした。
[日本語翻訳ガイド](https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/.github/CONTRIBUTING.md) に合わせて、半角スペースを追加しました。
#94 にしたがって、表記ゆれを修正しました。
close #220
=> Migration > Keycode Modifiers の翻訳を追従

src/guide/migration/attribute-coercion.md
Migration > Attribute Coercion を master に追従しました。
ref. #204 
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/attribute-coercion.md
前回からの差分
https://github.com/vuejs/docs-next/commit/639940b6154e318b0b26fd4a394defaa82eb45ba#diff-b479f35a5791f7d2ecdce48c7b3e621263cb53117bcf03bc2e7cf9a020974f49
表のマークダウンをフォーマットしたのみなので、翻訳の差分はありませんでした。
[日本語翻訳ガイド](https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/.github/CONTRIBUTING.md)にあわせて、2点修正しました。
振舞い -> 振る舞い
<details>
<summary>送り仮名の検索結果</summary>
```
❯ rg '振る舞い'
src/api/application-api.md
175:  アプリケーションスコープ全体に mixin を適用します。一度登録された場合、該当のアプリケーション内の任意のコンポーネントのテンプレートで利用することができます。プラグイン作者がコンポーネントにカスタムの振る舞いを注入するために使用することができます。**アプリケーションコードでは推奨されません。**.
src/style-guide/README.md
133:サブツリーの内部コンポーネントの状態を維持するために、コンポーネントでの `v-for` には …
```
=> Migration > Attribute Coercion の翻訳を追従

src/guide/migration/render-function-api.md
Migration > Render function api を master に追従しました。
ref. #225 
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/render-function-api.md
前回からの差分
https://github.com/vuejs/docs-next/commit/706a8cdeb0a6ff5aea4b8d6d7ed1996c785274fd#diff-aa744c862c8dae7617ad8685224b3f8e80bed656707d8716b00b9e9069789a51
https://github.com/vuejs/docs-next/commit/97574c9d0b308200f9a286464f79830ef170ac31#diff-aa744c862c8dae7617ad8685224b3f8e80bed656707d8716b00b9e9069789a51
https://github.com/vuejs/docs-next/commit/6cc3c7a899eea1e784eaba23813c176cbbc342c3#diff-aa744c862c8dae7617ad8685224b3f8e80bed656707d8716b00b9e9069789a51
close #225
=> Migration > Render Function Api の翻訳の追従

src/.vuepress/config.js, src/guide/mobile.md
Guide > Mobile の翻訳を追加しました。
https://v3.vuejs.org/guide/mobile.html
https://github.com/vuejs/docs-next/blob/master/src/guide/mobile.md
=> Guide > Mobile の翻訳

src/guide/list.md
Guide > List Rendering の翻訳を master に追従しました。
https://v3.vuejs.org/guide/list.html
https://github.com/vuejs/docs-next/blob/master/src/guide/list.md
ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/list.md
前回からの差分
https://github.com/vuejs/docs-next/commit/7cb38f933b0ff62e1d0568664d16161609c7cd8d#diff-d0e8e808e606120dd5e2584821a777b440131b6e2e14001f5b6443f41a8b6c16
https://github.com/vuejs/docs-next/commit/e554cd6f15fb201d8dc9e03e0f07e4a80e776f19#diff-d0e8e808e606120dd5e2584821a777b440131b6e2e14001f5b6443f41a8b6c16
https://github.com/vuejs/docs-next/commit/b8ef369093ac60541be01786d9a2273a5f4475f3#diff-d0e8e808e606120dd5e2584821a777b440131b6e2e14001f5b6443f41a8b6c16
https://github.com/vuejs/docs-next/commit/604de445d255b4456f431d094e2065b3d1bb0e90#diff-d0e8e808e606120dd5e258 …
=> Guide > List Rendering の翻訳を追従

src/guide/events.md
Guide > Event Handling の翻訳を master に追従しました。
https://v3.vuejs.org/guide/events.html
https://github.com/vuejs/docs-next/blob/master/src/guide/events.md
ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/events.md
前回からの差分
https://github.com/vuejs/docs-next/commit/86aa0c6278c3c7257e20e1340aefad9896345ef8#diff-1c7fe52c3423d851da9fe23f8e3e3a02d86a587d100ccbf423be254570dcdcc4
https://github.com/vuejs/docs-next/commit/5524819d9cd84394840d39cd333c2f0108c1bcae#diff-1c7fe52c3423d851da9fe23f8e3e3a02d86a587d100ccbf423be254570dcdcc4
https://github.com/vuejs/docs-next/commit/722b92ee0eb2e7f4ad64092481b6b70932b6209a#diff-1c7fe52c3423d851da9fe23f8e3e3a02d86a587d100ccbf423be254570dcdcc4
#272 でマージ済みです
=> Guide > Event Handling の翻訳を追従

src/guide/migration/attrs-includes-class-style.md
Textlint のエラーが発生していた箇所を修正しました。
「HTML」の前後にスペースを追加しました。
```
$ node -e "var shell=require('shelljs');var files=shell.find(['./src/**/*.md']).filter(function(file){return !file.endsWith('/guide/team.md')}).join(' ');if(shell.exec('textlint --rulesdir ./node_modules/textlint-checker-for-vuejs-jp-docs/rules/textlint-rule-vue-jp-docs -f pretty-error '+files).code!==0){shell.exit(1)};"
textlint-rule-vue-jp-docs: 半角と全角の間は一文字あける :  [Lが] ... ...以下のHTMLが生成されます:
/home/runner/work/ja.vuejs.org/ja.vuejs.org/src/guide/migration/attrs-includes-class-style.md:41:1
v
40. 
41. ...以下のHTMLが生成されます:
42. 
^
textlint-rule-vue-jp-docs: 半角と全角の間は一文字あける :  [Lが] ...  には、すべての属性が含まれているので、すべての属性を別の要素に適用することが簡単にできます。先ほどの例は、次のHTMLが生成されます:
/home/runner/work/ja.vuejs.org/ja.vuejs.org/src/guide/migration/attrs-includes-class-st …
```
=> Textlint エラーの修正

src/guide/custom-directive.md
Guide > Reusability & Composition > Custom Directives の翻訳を追従しました。
https://v3.vuejs.org/guide/custom-directive.html
https://github.com/vuejs/docs-next/blob/master/src/guide/custom-directive.md
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/custom-directive.md
前回からの差分
https://github.com/vuejs/docs-next/commit/c4b734d39bfeb73089bac2e525133ee48759e001#diff-91618a748fbcef0b7ce1f26f300d5aabe925114da5a69022eef7d42a7ed4d3bf
https://github.com/vuejs/docs-next/commit/dee5886588de85522a28f7f284d581dcfe67f7d8#diff-91618a748fbcef0b7ce1f26f300d5aabe925114da5a69022eef7d42a7ed4d3bf
https://github.com/vuejs/docs-next/commit/c9b8954c4012fd591a451dc5a92943e7b85c9ebb#diff-91618a748fbcef0b7ce1f26f300d5aabe925114da5a69022eef7d42a7ed4d3bf
autofocus のタイポを修正しました
=> Guide > Reusability & Composition > Custom Directives の翻訳を追従

src/guide/a11y-basics.md
Guide > Accessibility > Basics の翻訳を追従しました。
https://v3.vuejs.org/guide/a11y-basics.html
ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/a11y-basics.md
前回からの差分
https://github.com/vuejs/docs-next/commit/beb65fbd5562f233a0ad0a16f9496541b25055e8#diff-87162cc46e3a6b07566bab1abe9cd2ace23a1df367d04d038a0658e1a376e939
https://github.com/vuejs/docs-next/commit/0f25a8dbbb75d44c4b0466a2fd95d511b33b697f#diff-87162cc46e3a6b07566bab1abe9cd2ace23a1df367d04d038a0658e1a376e939
=> Guide > Accessibility > Basics の翻訳を追従

src/guide/a11y-semantics.md
Guide > Accessibility > Semantics の翻訳を追従しました。
https://v3.vuejs.org/guide/a11y-semantics.html
ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/a11y-semantics.md
前回からの差分
https://github.com/vuejs/docs-next/commit/a8385eaa9643dcdd521d9e926b9b9b6b9166f7fa#diff-4afbccbc62cfa9b1d4d1c0723f2ef22f44e491f7dd61232374103e8f7e822347
https://github.com/vuejs/docs-next/commit/d622347a867dda58fa4adcf08ca7212483a71f52#diff-4afbccbc62cfa9b1d4d1c0723f2ef22f44e491f7dd61232374103e8f7e822347
=> Guide > Accessibility > Semantics の翻訳を追従

src/guide/component-attrs.md
Guide > Components In-Depth > Non-Prop Attributes の翻訳を追従しました。
https://v3.vuejs.org/guide/component-attrs.html
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/component-attrs.md
前回からの差分
https://github.com/vuejs/docs-next/commit/b7b3202f101bd02548889f548cff5e54fbc6aac7#diff-a138928b9b9118041756d7258dcce0ebd883bb961eea6a3fed933509741e3408
https://github.com/vuejs/docs-next/commit/5092c4f1dc9f7ebe3011024a5504136d8a723b42#diff-a138928b9b9118041756d7258dcce0ebd883bb961eea6a3fed933509741e3408
=> Guide > Components In-Depth > Non-Prop Attributes の翻訳を追従

src/guide/component-provide-inject.md
Guide > Components In-Depth > Provide / inject の翻訳を追従しました。
https://v3.vuejs.org/guide/component-provide-inject.html
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/component-provide-inject.md
前回からの差分
https://github.com/vuejs/docs-next/commit/96d64039aa13770ab44f5c5ed46b387439014024#diff-e2d6d7ad2f53f101c031a6a845ead5917445c9a7745f832ecb079d8d319c9258
https://github.com/vuejs/docs-next/commit/3a40518f59d4b142a08e9a5e159ac12e8f2afbe9#diff-e2d6d7ad2f53f101c031a6a845ead5917445c9a7745f832ecb079d8d319c9258
https://github.com/vuejs/docs-next/commit/3804d0e2d63d490912125923b2aa524b8daf6720#diff-e2d6d7ad2f53f101c031a6a845ead5917445c9a7745f832ecb079d8d319c9258
=> Guide > Components In-Depth > Provide / inject の翻訳を追従

src/guide/component-dynamic-async.md
Guide > Componetns In-Depth > Dynamic & Async Components の翻訳を追従しました。
https://v3.vuejs.org/guide/component-dynamic-async.html
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/component-dynamic-async.md
前回からの差分
https://github.com/vuejs/docs-next/commit/e5b34b2bdbe3295f9fe33367a363577875c27d53#diff-49557730f09415eda33d758ddbdd6f3dcc8604204e87bcfb9ad76fd881dccf7f
内容の理解をしやすくするため、直訳的な箇所と、訳順を少し変更しました。
=> Guide > Componetns In-Depth > Dynamic & Async Components の翻訳を追従

src/guide/transitions-enterleave.md
Guide >  Enter & Leave Transitions の翻訳を追従しました。
https://v3.vuejs.org/guide/transitions-enterleave.html
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/transitions-enterleave.md
前回からの差分
https://github.com/vuejs/docs-next/commit/5d2a1e354fa23caa0972cef2833171dd384eff0f#diff-bd22f27bea3e777dd5f5f0393cc3bca3482956bf9a395876b15aefd64cdcbf65
https://github.com/vuejs/docs-next/commit/40e361ff407dfb1b95c79a75d53a0d55810bf087#diff-bd22f27bea3e777dd5f5f0393cc3bca3482956bf9a395876b15aefd64cdcbf65
https://github.com/vuejs/docs-next/commit/3f699dff18569229843691b8946057e7fe0f2ab9#diff-bd22f27bea3e777dd5f5f0393cc3bca3482956bf9a395876b15aefd64cdcbf65
(https://github.com/vuejs/docs-next/commit/722b92ee0eb2e7f4ad64092481b6b70932b6209a#diff-bd22f27bea3e777dd5f5f0393cc3bca3482956bf9a3958 …
=> Guide > Enter & Leave Transitions の翻訳を追従

src/guide/routing.md
Guide > Scaling Up > Routing の翻訳を追従しました。
https://v3.vuejs.org/guide/routing.html
ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/routing.md
前回からの差分
https://github.com/vuejs/docs-next/commit/da712359f8255d284e426bd271d690d16fdf6307#diff-c45fc2647705fe83e278fa345f8655c0f0b0e3729a998e8a698842aab60cc046
https://github.com/vuejs/docs-next/commit/e5b34b2bdbe3295f9fe33367a363577875c27d53#diff-c45fc2647705fe83e278fa345f8655c0f0b0e3729a998e8a698842aab60cc046
https://github.com/vuejs/docs-next/commit/b4b3eafe0dfb543a444da6d8910719d64133cdbc#diff-c45fc2647705fe83e278fa345f8655c0f0b0e3729a998e8a698842aab60cc046
=> Guide > Scaling Up > Routing の翻訳を追従

src/guide/state-management.md
Guide > Scaling Up > State Management の翻訳を追従しました。
https://v3.vuejs.org/guide/state-management.html
ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/state-management.md
前回からの差分
https://github.com/vuejs/docs-next/commit/0e5b6786d613eaa931f96310e6f5c48a2974a9cd#diff-e1a9e26e68d5a2cb4623864fbd565e0f3b01a6e17de1d884678f5130c64d52cd
https://github.com/vuejs/docs-next/commit/e5b34b2bdbe3295f9fe33367a363577875c27d53#diff-e1a9e26e68d5a2cb4623864fbd565e0f3b01a6e17de1d884678f5130c64d52cd
=> Guide > Scaling Up > State Management の翻訳を追従

src/guide/transitions-overview.md
Guide > Transitions & Animation > Overview の翻訳を追従しました。
https://v3.vuejs.org/guide/transitions-overview.html
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/transitions-overview.md
前回からの差分
https://github.com/vuejs/docs-next/commit/b6e51803ec75f8a7c71dd47258e5a4f2ce561e63#diff-fde31612563ef76bc7c64c34261c10bc6528d94c635352cefec6f67f5cae15f0
https://github.com/vuejs/docs-next/commit/4c0ff767bee3aeeb49e3a164110523ec8b469cd6#diff-fde31612563ef76bc7c64c34261c10bc6528d94c635352cefec6f67f5cae15f0
https://github.com/vuejs/docs-next/commit/beb65fbd5562f233a0ad0a16f9496541b25055e8#diff-fde31612563ef76bc7c64c34261c10bc6528d94c635352cefec6f67f5cae15f0
(vuejs/docs-next@722b92e#diff-bd22f27bea3e777dd5f5f0393cc3bca3482956bf9a395876b15aefd64cdcbf65 の差分は、すでにGuide > Introduction …
=> Guide > Transitions & Animation > Overview の翻訳を追従

src/guide/render-function.md
Guide > Reusability & Composition > Render functions の翻訳を追従しました。
https://v3.vuejs.org/guide/render-function.html
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/render-function.md
前回からの差分
https://github.com/vuejs/docs-next/commit/706a8cdeb0a6ff5aea4b8d6d7ed1996c785274fd#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/9ae70db2aa1145b27bdd301729f79c6c1bb7ba1c#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/dbeed5b73a88d8c8852a52626e9e431fe47ea991#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/e554cd6f15fb201d8dc9e03e0f07e4a80e776f19#diff-0b635f32793fe88d869035c17f5143d6a7011183741 …
=> Guide > Reusability & Composition > Render functions の翻訳を追従

src/guide/reactivity-fundamentals.md
Guide > Advanced Guides > Reactivity Fundamentals の翻訳を追従しました。
https://v3.vuejs.org/guide/reactivity-fundamentals.html
ファイル更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/reactivity-fundamentals.md
前回からの差分
https://github.com/vuejs/docs-next/commit/3e5e52e9fdd3abbaab19849dc0dd81752d216216#diff-55ff289006ef954900bf36417b8e59c1586919dd6ca8d8047d053517cacb8a97
https://github.com/vuejs/docs-next/commit/d7b0ca0da562cbb2e5bf015607d008b6ed178ade#diff-55ff289006ef954900bf36417b8e59c1586919dd6ca8d8047d053517cacb8a97
https://github.com/vuejs/docs-next/commit/f9828e0e2768fca4e0653fec7217792b3e3be361#diff-55ff289006ef954900bf36417b8e59c1586919dd6ca8d8047d053517cacb8a97
=> Guide > Advanced Guides > Reactivity Fundamentals の翻訳を追従

src/guide/ssr/structure.md
Guide > Server-Side Rendering Guide > Source Code Structure の翻訳をしました
https://v3.vuejs.org/guide/ssr/structure.html
=> Guide > Server-Side Rendering Guide > Source Code Structure の翻訳

.github/workflows/che-tsumi.yaml
Set at #324
Fork 先での動作確認が取れたので、che-tsumi-next の GitHub Action を追加します。
close #324
=> feat: add che-tsumi github action

src/guide/ssr/build-config.md
Guide > Server-Side Rendering Guide > Build Configuration の翻訳をしました。
https://v3.vuejs.org/guide/ssr/build-config.html
別途原文の方に PR 出しますが、ホワイトリスト->許可リストに翻訳しています。
=> Guide > Server-Side Rendering Guide > Build Configuration の翻訳

src/guide/ssr/server.md
Guide > Server-Side Rendering Guide > Server Configuration の翻訳をしました。
https://v3.vuejs.org/guide/ssr/server.html
=> Guide > Server-Side Rendering Guide > Server Configuration の翻訳

src/guide/ssr/routing.md
Guide > Server-Side Rendering Guide > Routing and Code-Splitting の翻訳をしました。
https://v3.vuejs.org/guide/ssr/routing.html
=> Guide > Server-Side Rendering Guide > Routing and Code-Splitting の翻訳
