- src/guide/optimizations.md
> Render Mechanisms > Rendering Mechanisms and Optimizations

- src/guide/introduction.md
> docs: Translate Essentials > Introduction

- src/guide/instance.md
Fixes #4: Essentials -> The Application Instanceの翻訳
> docs: Essentials > The Application Instance

- src/guide/state-management.md
resolve #43 Scaling Up > State Management の翻訳
> docs: #43 Scaling Up > State Management の翻訳

- src/guide/typescript-support.md
fix #53  (resolves #41)
- 英語原文が残っていた部分を削除しました。
- [このコメント](https://github.com/vuejs-jp/ja.vuejs.org/issues/1#issuecomment-695164725)への[回答](https://github.com/vuejs-jp/ja.vuejs.org/issues/1#issuecomment-695877484)にもとづき、「ノート」を「Note」に戻しました。
> Tooling > TypeScript Support

- src/guide/render-function.md
Reusability & Composition > Render Functionsの翻訳
> Reusability & Composition > Render Functions (#28)

- src/guide/testing.md
resolve #40
Translate Tooling > Testing の翻訳
> docs: Translate Tooling > Testingの翻訳

- src/guide/component-slots.md
resolves https://github.com/vuejs-jp/ja.vuejs.org/issues/16
https://deploy-preview-105--vuejs-v3-ja-doc-preview.netlify.app/guide/component-slots.html で動作を確認できます
> Components In-Depth > Slots の翻訳

- src/guide/migration/introduction.md
Resolve #106
翻訳時点で最新版のドキュメントを対象にして翻訳をしています。
https://github.com/vuejs/docs-next/blob/3be5dbadc8e2ed5500d2bb68204e2f706ccdefdb/src/guide/migration/introduction.md
> Migration Guide > Introduction  の翻訳

- src/style-guide/README.md
#138 の `Style Guide 冒頭 / Rule Categories` の翻訳
基本的に下記の Vue 2 のスタイルガイドと内容が同じだったため、ほんの少しだけ翻訳に手直しを入れただけのプルリクエストになっています。
https://jp.vuejs.org/v2/style-guide/#%E3%83%AB%E3%83%BC%E3%83%AB%E3%82%AB%E3%83%86%E3%82%B4%E3%83%AA
> translate Style Guide / Rule Categories

- .github/workflows/sync.yaml
https://github.com/vuejs-jp/ja.vuejs.org/runs/1366347879?check_suite_focus=true
name の期待動作に沿うようにワークフローを修正しました
> fix(ci): update sync workflow

- src/style-guide/README.md
#138 の `Priority A` の翻訳
本日(2020/11/14)時点で最新のコミットを元に翻訳を行いました。
https://github.com/vuejs/docs-next/blob/0e5b6786d613eaa931f96310e6f5c48a2974a9cd/src/style-guide/README.md
> Translate Style Guide / Priority A

- src/guide/transitions-list.md
resolve #23
長らく滞っていましたが、この List Transition に対しての翻訳を終えました。
> doc: Tranlate list transition

- src/guide/component-basics.md
> fix: "コンポーネントの基本"の原文との差異及び誤りの修正 (#186)

- src/guide/component-custom-events.md
残ったままになっている原文を削除しました
Closes #188
> Remove any remaining original text (#188)

- src/guide/migration/async-components.md
ref. #203
Migration > Async Components を本家の master に追従しました。
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/async-components.md
前回からの差分
https://github.com/vuejs/docs-next/commit/9d48e280d3862fc951d1c821cd4e863a7b56efba#diff-810cfc1a42d27b7b308a29e3c5c72f09aff1279ff9b91ceef811e2b1d2beb06b
close #203
> Migration > Async Components の翻訳を追従

- src/.vuepress/config.js
- src/guide/migration/children.md
Migration > Children を本家の master に追従しました。
ref. #206
close #206
> Migration > Children の翻訳を追従

- src/guide/migration/inline-template-attribute.md
Migration > Inline Template Attribute を本家の master に追従しました。
ref. #217 
本家の更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/inline-template-attribute.md
前回からの差分
https://github.com/vuejs/docs-next/commit/0391e2eb054aa2877259e72c8f1741fc9eaf6252#diff-49a42eb1529a6cd9491644a7bd350e66377170aa56e92a88513c9f864531b199
close #217
> Migration > Inline Template Attribute の翻訳を追従

- src/.vuepress/config.js
- src/guide/migration/suspense.md
Migration > Suspense を本家の master に追従しました。
ref. #227 
close #227
> Migration > Suspense の翻訳を追従

- src/.vuepress/config.js
- src/api/index.md
#201 を進めるにあたって、ナビゲーションの不一致で公式ドキュメントと日本語訳ドキュメントが比較がしづらい。
公式の [Vue Press 設定](https://github.com/vuejs/docs-next/blob/master/src/.vuepress/config.js)に追従しつつ、次の2点をコメントアウトで除いておきます。
- 日本語訳ファイルがまだなく 404 エラーになるもの
- PWA 対応など、公式に取り込まれているが、日本語ドキュメントではまだ取り込んでいないもの
公式に追いついたものから、コメントアウトを取り除いて公開していければなと。
#248, #250, #251 とはコンフリクトするため、この pull request はそれらすべてマージされてからが望ましいです。
> サイドバーのメニューを更新

- src/guide/computed.md
Guide > Computed Properties and Watchers の翻訳を master に追従しました。
https://v3.vuejs.org/guide/computed.html
https://github.com/vuejs/docs-next/blob/master/src/guide/computed.md
ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/computed.md
前回からの差分
https://github.com/vuejs/docs-next/commit/c39a08e5927e44d69ce7462425cd829276ea4575#diff-03e390df8220bc308731391592aa75bfd10d525fc7b89fd0668d88f4b625855a
> Guide > Computed Properties and Watchers の翻訳を追従

- src/guide/composition-api-lifecycle-hooks.md
Guide > Composition API > Lifecycle Hooks の翻訳を追従
https://v3.vuejs.org/guide/composition-api-lifecycle-hooks.html
https://github.com/vuejs/docs-next/blob/master/src/guide/composition-api-lifecycle-hooks.md
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/composition-api-lifecycle-hooks.md
https://github.com/vuejs/docs-next/commit/1273ac41586004b6a8ce9e3ca044da435b186065#diff-0c45d18e190678e25a221aeb4a281fc3333f685cf95fbd861ae4647e5545f00e
原文のみの修正だったため、差分ありませんでした。
#94 にしたがって、いくつか表記揺れを修正しました。
> Guide > Composition API > Lifecycle Hooks の翻訳を追従

- src/guide/a11y-resources.md
Guide > Accessibility > Resources の翻訳を追従しました。
https://v3.vuejs.org/guide/a11y-resources.html
ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/a11y-resources.md
前回からの差分
https://github.com/vuejs/docs-next/commit/acfad05befbad0e3fc7f0612f5c7875fb33da073#diff-3b857cb2027053331e7052588f412bc8781d9f46a6d94b84b8551cf3009e4230
> Guide > Accessibility > Resources の翻訳を追従

- src/guide/plugins.md
Guide > Reusability & Composition > Plugins の翻訳を追従しました。
https://v3.vuejs.org/guide/plugins.html
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/plugins.md
前回からの差分
https://github.com/vuejs/docs-next/commit/29497add8f9007e7cce5900268c743a67720c9c8#diff-d21d313af550bd70eea62c2d32cec2617d9d8d4fbf5e542e59da46abca5b3ce0
> Guide > Reusability & Composition > Plugins の翻訳を追従

- src/guide/optimizations.md
Guide > Advanced Guides > Rendering Mechanisms and Optimizations の翻訳を追従しました。
https://v3.vuejs.org/guide/optimizations.html
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/optimizations.md
前回からの差分
https://github.com/vuejs/docs-next/commit/4f326b9c2d955b1c5c916c56a365e0fd7894b885#diff-af6f049eff49e01d39ccdfbd15944babab94c1915c6c96df6a910f994d774495
> Guide > Advanced Guides > Rendering Mechanisms and Optimizations の翻訳を追従

- src/guide/ssr/universal.md
Guide > Server-Side Rendering Guide > Universal の翻訳をしました
https://v3.vuejs.org/guide/ssr/universal.html
「Universal」がそろそろ一般化してきてると思うので、最初の見出しではカタカナの補足いれましたが、以降は英単語のままにしています。
> Guide > Server-Side Rendering Guide > Universal の翻訳
